name: qcnn_env_lppc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - matplotlib
  - seaborn
  - pennylane
  - numpy
  - jax
  - optax
  - pandas
  - scikit-learn
  - torch
  - pip
  - pip:
    - absl-py
    - aiohttp
    - aiosignal
    - appdirs
    - autograd
    - autoray
    - cachetools
    - charset-normalizer
    - chex
    - contourpy
    - cycler
    - datasets
    - dill
    - etils
    - fsspec
    - frozenlist
    - future
    - huggingface-hub
    - idna
    - jaxlib
    - joblib
    - kiwisolver
    - markupsafe
    - ml-dtypes
    - mpmath
    - multidict
    - multiprocess
    - networkx
    - opt-einsum
    - pillow
    - platformdirs
    - pyarrow
    - pyarrow-hotfix
    - pyparsing
    - python-dateutil
    - pytz
    - rustworkx
    - scipy
    - semantic-version
    - sympy
    - threadpoolctl
    - toolz
    - tqdm
    - typing_extensions
    - tzdata
    - urllib3
    - xxhash
    - yarl
